// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fzfqbblmtcrrixroznmv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ6ZnFiYmxtdGNycml4cm96bm12Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzMTc3ODMsImV4cCI6MjA1Nzg5Mzc4M30.mLcS95wgUcOBGteVkC3WqQIjJz-AJt2OOH2jZLH1JlA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);